[build-system]
requires = [
    "setuptools",
    "scikit-build>=0.15",
    "cmake",
    "ninja",
    "numpy>=1.21",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
